# Generated by Django 4.2.16 on 2024-09-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'default_related_name': 'custom_blogpage'},
        ),
    ]
